export enum QueryKeys {
  AUTHORIZATION = 'authorization',
  CART = 'cart',
  CART_ITEM = 'cart-item',
  CART_ITEMS = 'cart-items',
  CONTACT = 'contact',
  COMPANY = 'company',
  COMPANY_FULL = 'company-full',
  DASHBOARD = 'dashboard',
  BILLING = 'billing',
  FAVORITES = 'favorites',
  ORDER = 'order',
  ORDERS = 'orders',
  PRODUCT = 'product',
  PRODUCT_WITH_VARIANTS = 'product-with-variants',
  PRODUCTS = 'products',
  PRODUCTS_WITH_VARIANTS = 'products-with-variants',
  SHIPPING = 'shipping',
  SIZE = 'size',
  USER = 'user',
  USER_FULL = 'user-full',
  USER_STATUS = 'user-status',
  VARIANT = 'variant',
  VARIANT_WITH_PRODUCT = 'variant-with-product',
  VARIANTS = 'variants',
}
