export enum QueryKeys {
  CART = 'cart',
  CART_ITEM = 'cart-item',
  CART_ITEMS = 'cart-items',
  DASHBOARD = 'dashboard',
  FAVORITES = 'favorites',
  ORDER = 'order',
  ORDERS = 'orders',
  PRODUCT = 'product',
  PRODUCTS = 'products',
  SHIPPING = 'shipping',
  SIZE = 'size',
  USER_STATUS = 'user-status',
  VARIANT = 'variant',
  VARIANTS = 'variants',
}
